version: "3.8"
services:
  pihole:
    image: pihole/pihole
    container_name: pihole
    restart: unless-stopped
    ports:
      - "8053:53/tcp"
      - "8053:53/udp"
      - "80:80"
      - "443:443"
    environment:
      - TZ=Etc/UTC
      - WEBPASSWORD=yourpassword
    volumes:
      - ./pihole/etc-pihole:/etc/pihole
      - ./pihole/etc-dnsmasq.d:/etc/dnsmasq.d
    cap_add:
      - NET_ADMIN 