version: '3.8'

services:
  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Dublin
    volumes:
      - /home/YOUR_USER/docker/radarr:/config
      - /media/movies:/movies
      - /media/downloads:/downloads
    ports:
      - 7878:7878
    restart: unless-stopped 