version: '3.8'

services:
  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Dublin
    volumes:
      - /home/YOUR_USER/docker/sonarr:/config
      - /media/tvseries:/tv
      - /media/downloads:/downloads
    ports:
      - 8989:8989
    restart: unless-stopped 